name: resale-flat-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.24
  - pandas>=1.5
  - plotly>=5.0
  - requests>=2.28
  - pip:
    - streamlit>=1.25
